---
- name: Demo playbook
  hosts: windows
  tasks:
    - win_ping:

    - win_file:
        path: C:\foo.conf
        state: touch

    - win_stat:
        path: C:\foo.conf    

    - name: Check IPCONFIG
      ansible.windows.win_command: IPCONFIG

    - name: Get info for a single service
      ansible.windows.win_service_info:
      name: WinRM
      register: service_info

    - debug:
        msg:
          -  "{{ service_info.services[10].state }}"
          -  "{{service_info.services[10].name}}"  


    

    